version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SOME-PASSWORD
      MYSQL_DATABASE: reddit-clone
    ports:
      - "3306:3306"
